# Sample Compose file for Sanctuary services

name: sanctuary

x-env-common-dotnet: &common-dotnet
  DOTNET_gcServer: 0

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    user: "1000:1000"
    mem_limit: 512m
    command: --wiredTigerCacheSizeGB 0.25
    volumes:
      - ./mongodb-data:/data/db
    expose:
      - 27017
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  builder:
    image: sanctuary-census-builder:latest
    restart: unless-stopped
    user: "1000:1000"
    environment:
      <<: *common-dotnet
    volumes:
      - ./config/appsettings.builder.json:/app/appsettings.json:ro
      - ./sanctuary-census-diff:/home/app/sanctuary-census-diff
      - ./builder-app-data:/AppData
    depends_on:
      mongodb:
        condition: service_healthy
        restart: false

  api:
    image: sanctuary-census-api:latest
    restart: unless-stopped
    environment:
      <<: *common-dotnet
    volumes:
      - ./config/appsettings.api.json:/app/appsettings.json:ro
    expose:
      - 8080
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true

  realtimehub:
    image: sanctuary-census-realtimehub:latest
    restart: unless-stopped
    environment:
      <<: *common-dotnet
    volumes:
      - ./config/appsettings.realtimehub.json:/app/appsettings.json:ro
    expose:
      - 7041
      - 5062
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true

  rc1:
    image: sanctuary-census-realtimecollector:latest
    restart: unless-stopped
    environment:
      <<: *common-dotnet
    volumes:
      - ./config/appsettings.rc1.json:/app/appsettings.json:ro
    depends_on:
      - realtimehub
