using Sanctuary.Census.Common.Abstractions.Objects.Collections;
using Sanctuary.Census.Common.Attributes;
using Sanctuary.Census.Common.Objects.CommonModels;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Sanctuary.Census.Common.Objects.Collections;

#pragma warning disable CS1591
[Collection]
[Description("Specific properties of a weapon's firing characteristics")]
public record FireMode2
(
    [property:Key] uint FireModeID,
    byte FireModeTypeID,
    LocaleString Description,
    [property: Key] uint? AbilityID,
    uint? AmmoItemID,
    byte AmmoSlot,
    bool ArmorPenetration,
    bool Automatic,
    bool GriefImmune,
    bool LaserGuided,
    bool IronSights,
    bool SprintFire,
    bool SwayCanSteady,
    bool UseInWater,
    decimal CofOverride,
    decimal CofPelletSpread,
    decimal CofRange,
    decimal CofRecoil,
    decimal CofScalar,
    decimal CofScalarMoving,
    decimal? DamageHeadMultiplier,
    decimal? DamageLegsMultiplier,
    uint? DamageIndirectEffectID,
    byte FireAmmoPerShot,
    ushort FireAutoFireMs,
    byte FireBurstCount,
    ushort FireChargeUpMs,
    ushort FireCooldownDurationMs,
    ushort FireDelayMs,
    ushort FireDurationMs,
    ushort FireDetectRange,
    byte FirePelletsPerShot,
    ushort FireRefireMs,
    uint? HeatPerShot,
    ushort? HeatRecoveryDelayMs,
    uint? HeatThreshold,
    int MaxDamage,
    int MaxDamageRange,
    int MaxDamageInd,
    decimal MaxDamageIndRadius,
    int MinDamage,
    int MinDamageRange,
    int MinDamageInd,
    decimal MinDamageIndRadius,
    decimal MoveModifier,
    decimal TurnModifier,
    [property: Key] uint? PlayerStateGroupID,
    decimal? ProjectileSpeedOverride,
    decimal RecoilAngleMax,
    decimal RecoilAngleMin,
    decimal RecoilFirstShotModifier,
    decimal? RecoilHorizontalMax,
    decimal? RecoilHorizontalMaxIncrease,
    decimal? RecoilHorizontalMin,
    decimal? RecoilHorizontalMinIncrease,
    decimal? RecoilHorizontalTolerance,
    decimal? RecoilIncrease,
    decimal? RecoilIncreaseCrouched,
    decimal? RecoilMagnitudeMax,
    decimal? RecoilMagnitudeMin,
    decimal? RecoilMaxTotalMagnitude,
    decimal? RecoilRecoveryAcceleration,
    ushort? RecoilRecoveryDelayMs,
    decimal? RecoilRecoveryRate,
    byte? RecoilShotsAtMinMagnitude,
    ushort? ReloadAmmoFillMs,
    bool ReloadBlockAuto,
    ushort? ReloadChamberMs,
    bool ReloadContinuous,
    ushort? ReloadLoopStartMs,
    ushort? ReloadLoopEndMs,
    ushort ReloadTimeMs,
    int ShieldBypassPct,
    decimal? SwayAmplitudeX,
    decimal? SwayAmplitudeY,
    decimal? SwayPeriodX,
    decimal? SwayPeriodY,
    decimal ZoomDefault
) : ISanctuaryCollection;
#pragma warning restore CS1591
